name: 'jaffle_shop_1'
version: '1.0.0'

profile: 'jaffle_shop_1'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop_1:
    +materialized: view
